### ISSUE TITLE
Missing Pubs

### ISSUE THREAD

**Issue by drnickyoung** [lekovicj/Geography-of-Pub-Names#1]
Hi,

Excellent project. Watching it and might have a play. One question though, the extracted data (CSV) appears not to be complete. Is this the case or have I missed something?

For example many of the Thatcham Pubs do not show on the data:

Crickets - 51.40332 / -1.25900
White Hart - 51.40324 / -1.25836

Just two but there are more I cannot see in the data.

**Comment by drnickyoung** [comment]
Just wondering if it is because some pubs are placed as buildings and not points/nodes.

**Comment by lekovicj** [comment]
Hi Nick, thanks and good spot - looking back at the code, think I stopped short of finding a process for handling the polygons and multipolygons. Off the top of my head, would require turning them into points in some way. Will try to look into it, but if you've got any good pointers on code snippets that might help, do let me know.

**Comment by drnickyoung** [comment]
Hi,

Thought it might be that causing the issue.  Not that great on R, have done similar on other code. When I get chance I will take a look and see if I can figure it out.

**Comment by lekovicj** [comment]
Updated code and data file with a messy workaround (might need more tweaking), but the data file should include more pubs now. Thanks for flagging!
